apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  namespace: app-mesh-lab
  labels:
    app: ping
spec:
  selector:
    matchLabels:
      app: ping
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ping
        version: v1
    spec:
      containers:
        - name: ping
          image: strongjz/golang_example:0.0.4
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /data
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8080
            - containerPort: 8090
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "mysecretpassword"
            - name: DB_PORT
              value: "5432"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  namespace: app-mesh-lab
spec:
  selector:
    matchLabels:
      app: data
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: data
        version: v1
    spec:
      containers:
        - name: data
          image: strongjz/golang_example:0.0.4
          ports:
            - containerPort: 8080
            - containerPort: 8090
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "mysecretpassword"
            - name: DB_PORT
              value: "5432"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: app-mesh-lab
spec:
  selector:
    matchLabels:
      app: admin
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
        version: v1
    spec:
      containers:
        - name: admin
          image: strongjz/golang_example:0.0.4
          ports:
            - containerPort: 8080
            - containerPort: 8090
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "mysecretpassword"
            - name: DB_PORT
              value: "5432"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName