apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /ping(/|$)(.*)
            backend:
              serviceName: ping-service
              servicePort: 8080
          - path: /data(/|$)(.*)
            backend:
              serviceName: data-service
              servicePort: 8080
          - path: /admin(/|$)(.*)
            backend:
              serviceName: admin-service
              servicePort: 8080