apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l4-rule"
spec:
  endpointSelector:
    matchLabels:
      app: app
  ingress:
    - toPorts:
        - ports:
            - port: "8080"
              protocol: TCP