apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curl2
  name: curl2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl2
  template:
    metadata:
      labels:
        app: curl2
    spec:
      containers:
        - image: radial/busyboxplus:curl
          command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
          imagePullPolicy: Always
          name: curl2
          ports:
            - containerPort: 5678
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
