apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: admin-port
      protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer