apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  namespace: app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
      - http:
        paths:
          - path: /ping
            backend:
              serviceName: ping
              servicePort: 80
          - path: /admin
            backend:
              serviceName: ping
              servicePort: 80
          - path: /data
            backend:
              serviceName: ping
              servicePort: 80